export const LOGIN = "LOGIN";
export const SET_TOKEN = "SET_TOKEN";
export const LOGOUT = "LOGOUT";
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const CHANGE_CUSTOMER_SELECTED_PRODUCT = "CHANGE_CUSTOMER_SELECTED_PRODUCT";
export const CHANGE_ADMIN_SELECTED_PRODUCT = "CHANGE_ADMIN_SELECTED_PRODUCT";
export const GET_CART = "GET_CART";
export const GET_SHOPPING_LIST = "GET_SHOPPING_LIST";