/* Authentication */
export const LOGIN = "LOGIN";
export const SET_TOKEN = "SET_TOKEN";
export const LOGOUT = "LOGOUT";
export const UNAUTH = "UNAUTH";

/* Getters */
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const CHANGE_CUSTOMER_SELECTED_PRODUCT = "CHANGE_CUSTOMER_SELECTED_PRODUCT";
export const CHANGE_ADMIN_SELECTED_PRODUCT = "CHANGE_ADMIN_SELECTED_PRODUCT";
export const GET_CART = "GET_CART";
export const GET_SHOPPING_LIST = "GET_SHOPPING_LIST";
export const GET_USERS = "GET_USERS";
export const GET_MANUFACTURERS = "GET_MANUFACTURERS"; 
export const GET_LOCALES = "GET_LOCALES";
export const GET_CURRENCIES = "GET_CURRENCIES";
export const PERFORM_SEARCH = "PERFORM_SEARCH";

/* Notifications */
export const ADD_PRODUCT_NOTIFICATION = "ADD_PRODUCT_NOTIFICATION";
export const ADD_PRODUCT_NOTIFICATION_ERROR = "ADD_PRODUCT_NOTIFICATION_ERROR";
export const EDIT_PRODUCT_NOTIFICATION = "EDIT_PRODUCT_NOTIFICATION";
export const EDIT_PRODUCT_NOTIFICATION_ERROR = "EDIT_PRODUCT_NOTIFICATION_ERROR";
export const REMOVE_PRODUCT_NOTIFICATION = "REMOVE_PRODUCT_NOTIFICATION";
export const REMOVE_PRODUCT_NOTIFICATION_ERROR = "REMOVE_PRODUCT_NOTIFICATION_ERROR";
export const ADD_PROD_TO_CART_NOTIFICATION = "ADD_PROD_TO_CART_NOTIFICATION";
export const ADD_PROD_TO_CART_NOTIFICATION_ERROR = "ADD_PROD_TO_CART_NOTIFICATION_ERROR";
export const REMOVE_PRODUCT_FROM_CART_NOTIFICATION = "REMOVE_PRODUCT_FROM_CART_NOTIFICATION";
export const REMOVE_PRODUCT_FROM_CART_NOTIFICATION_ERROR = "REMOVE_PRODUCT_FROM_CART_NOTIFICATION_ERROR";
export const PERFORM_CHECKOUT_NOTIFICATION = "PERFORM_CHECKOUT_NOTIFICATION";
export const PERFORM_CHECKOUT_NOTIFICATION_ERROR = "PERFORM_CHECKOUT_NOTIFICATION_ERROR";

/* UI */
export const CHANGE_SELECTED_MENU_BTN = "CHANGE_SELECTED_MENU_BTN";